-- Drop table if exists
IF OBJECT_ID('RAIS_FatoMovimentacaoTrabalhadores', 'U') IS NOT NULL
    DROP TABLE RAIS_FatoMovimentacaoTrabalhadores;

-- Create table
CREATE TABLE RAIS_FatoMovimentacaoTrabalhadores (
    COD_OCUPACAO INT,
    COD_SUBCLASSE INT,
    COD_GRAU_INSTRUCAO INT,
    COD_FAIXA_ETARIA INT,
    COD_FAIXA_HORA_CONTRATUAL INT,
    COD_FAIXA_REMUNERACAO_MEDIA_DEZEMBRO INT,
    COD_FAIXA_REMUNERACAO_MEDIA_ANO INT,
    COD_FAIXA_TEMPO_EMPREGO INT,
    TRABALHADOR_PCD NVARCHAR(MAX),
    EMPRESA_OPTANTE_SIMPLES NVARCHAR(MAX),
    ANO_RAIS INT,
    DATA_ADMISSAO DATE,
    DATA_DEMISSAO DATE,
    COD_MOTIVO_DESLIGAMENTO INT,
    COD_MUNICIPIO_SERVICO_PRESTADO INT,
    COD_NATUREZA_JURIDICA INT,
    QTD_HORAS_CONTRATUAIS INT,
    COD_RACA_COR INT,
    COD_SEXO_TRABALHADOR INT,
    COD_TAMANHO_ESTABELECIMENTO INT,
    TEMPO_EMPREGADO FLOAT,
    COD_TIPO_ADMISSAO INT,
    COD_TIPO_DEFICIENCIA INT,
    COD_TIPO_EMPREGATICIO INT,
    VINCULO_ATIVO_DEZEMBRO NVARCHAR(MAX),
    COD_FAIXA_SALARIAL_MEDIA_DEZEMBRO INT,
    VALOR_REMUNERACAO_DEZEMBRO FLOAT,
    COD_FAIXA_SALARIAL_MEDIA_ANO INT,
    VALOR_REMUNERACAO_MEDIA FLOAT,
    IDADE_TRABALHADOR INT,
    COD_MUNICIPIO_ESTABELECIMENTO INT,
    COD_NACIONALIDADE INT,
    TRABALHADOR_INTERMITENTE NVARCHAR(MAX),
    TRABALHADOR_PARCIAL NVARCHAR(MAX)
);