--sqlite
DROP  TABLE MEC_DimCBO;
CREATE TABLE MEC_DimCBO
(
    COD_GRANDE_GRUPO 		INT,
    COD_SUBGRUPO_PRINCIPAL  INT,
    COD_SUBGRUPO 			INT,
    COD_OCUPACAO 			INT,
    GRANDE_GRUPO 			NVARCHAR(MAX),
    SUBGRUPO_PRINCIPAL 		NVARCHAR(MAX),
    SUBGRUPO 				NVARCHAR(MAX),
    OCUPACAO 				NVARCHAR(MAX),
    CURSO_TECNICO 			NVARCHAR(MAX),
    CHAVE_CURSO_TECNICO 	NVARCHAR(MAX)
);

--sqlite
DROP  TABLE MEC_StgCBO;
CREATE TABLE MEC_StgCBO (
    COD_GRANDE_GRUPO 		NVARCHAR(max),
    COD_SUBGRUPO_PRINCIPAL 	NVARCHAR(max),
    COD_SUBGRUPO 			NVARCHAR(max),
    COD_FAMILIA 			NVARCHAR(max),
    COD_OCUPACAO 			NVARCHAR(max),
    SGL_GRANDE_AREA 		NVARCHAR(max),
    NOME_GRANDE_AREA 		NVARCHAR(max),
    COD_ATIVIDADE 			NVARCHAR(max),
    NOME_ATIVIDADE 			NVARCHAR(max),
    GRANDE_GRUPO 			NVARCHAR(max),
    SUBGRUPO_PRINCIPAL 		NVARCHAR(max),
    SUBGRUPO 				NVARCHAR(max),
    SINONIMO 				NVARCHAR(max),
    OCUPACAO 				NVARCHAR(max),
    FAMILIA 				NVARCHAR(max),
    CURSO_TECNICO 			NVARCHAR(max),
    CHAVE_CURSO_TECNICO 	NVARCHAR(max)


--sql server
CREATE TABLE Stg_CBOTecnicos (.
		CURSO				NVARCHAR(max),
		COD_OCUPACAO		NVARCHAR(max),
		CHAVE_CURSO_TECNICO NVARCHAR(max)

);
